name: "Nethermind - Bridge UI - Docker build and push"

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "bridge-ui-v*"
    paths:
      - "packages/bridge-ui/**"

env:
  DOCKER_REGISTRY: nethermind.jfrog.io
  DOCKER_USERNAME: core
  DOCKER_REPOSITORY: core-oci-local-dev/bridge-ui

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    if: github.repository == 'NethermindEth/surge-taiko-mono'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_CORE_TOKEN_CONTRIBUTOR }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: packages/bridge-ui
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Summary
        run: |
          echo "## Docker build completed :green_circle:" >> $GITHUB_STEP_SUMMARY
          echo "### Tags" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r TAG; do
            echo "- $TAG" >> $GITHUB_STEP_SUMMARY
          done
